---
apiVersion: v1
kind: Namespace
metadata:
  name: fox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fox-app
  namespace: fox
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fox-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fox-app
    spec:
      containers:
      - image: infx06037/mario
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1 
kind: Service 
metadata: 
  name: fox-app-svc 
  namespace: fox
spec: 
  type: LoadBalancer
  selector: 
    app: fox-app
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 